### ISSUE TITLE
console-plugin-gpu container image is not accessible

### ISSUE THREAD

**Issue by patrickstrick** [rh-ecosystem-edge/console-plugin-nvidia-gpu#20]
After running `helm install -n nvidia-gpu-operator console-plugin-nvidia-gpu rh-ecosystem-edge/console-plugin-nvidia-gpu`, the pod "console-plugin-nvidia-gpu-xxxxx" goes into ImagePullBackOff due to the following error:

```Failed to pull image "quay.io/edge-infrastructure/console-plugin-gpu:latest": rpc error: code = Unknown desc = reading manifest latest in quay.io/edge-infrastructure/console-plugin-gpu: unauthorized: access to the requested resource is not authorized```

I saw that you recently renamed some things from "console-plugin-gpu" to "console-plugin-nvidia-gpu" (#9) and see there is a matching "edge-infrastructure / console-plugin-nvidia-gpu" repo on Quay.io. Does the container image need updated to match in the Deployment?

**Comment by rawagner** [comment]
@patrickstrick Thanks for reporting the issue. We did not recreate helm repo chart after https://github.com/rh-ecosystem-edge/console-plugin-nvidia-gpu/pull/18 .
Fix https://github.com/rh-ecosystem-edge/console-plugin-nvidia-gpu/pull/22

**Comment by rawagner** [comment]
#22 is merged. closing.
